# Generated by Django 6.1.1 on 2026-09-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visual_type',
            field=models.CharField(default='standard', max_length=30),
        ),
    ]
