# Generated by Django 6.1.1 on 2026-09-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MUHAMMED ADGOLIGN', max_length=200)),
                ('role', models.CharField(default='Nuclear Engineering Student - Software Developer - Researcher', max_length=300)),
                ('description', models.TextField(blank=True, default='Nuclear Engineering student, software developer, and researcher passionate about software development, engineering research, and building practical technical projects.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
