# Generated by Django 6.1.1 on 2026-10-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Information', 'verbose_name_plural': 'Contact Information'},
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
